name: practica6
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  path_provider: ^2.1.1
  sqflite: ^2.3.0
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  location: ^5.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
